### ISSUE TITLE
cant remove field

### ISSUE THREAD

**Issue by marcin-derlukiewicz** [sardoj/VTModuleDesigner#1]
i opened module with designer
and i'm trying to remove field by dragging it to trash and saving by make and install.

only raised version of module is saved.
uitype of field is 56 it's in first block (LBL_BLOCK_SYSTEM_INFORMATION)

**Comment by sardoj** [comment]
Hello,
In fact there is a problem with Vtiger Core, particulary with UpdatePackage.php.
The function to update blocks is not complete and it is not possible for the moment to remove fields.

But if you unzip the module package, made by Module Design, and see the manifest.xml file, the field is well removed.
