### ISSUE TITLE
Table cancellation after Picklist field delete

### ISSUE THREAD

**Issue by ardennext99** [sardoj/VTModuleDesigner#130]
Hi,
First of all thanks a lot for your job.
Then, i've found an issue in when deleting a picklist field.
those are the step to reproduce:

1) Create a custom module with other fields and a picklist, then install it
2) Reopen the custom module and delete the picklist field

now if you go to the database the tables used for this field is still present, and there are no way to indentify and delete by UI. can you implement the check & delete procedure to include in the saving step?

Thanks a lot, bye

**Comment by playmono** [comment]
Hi,

With these steps its normal that if you go to the database, tables for picklist will remains there. With this steps you are changing the "on fly" module (then you will export or install).

If you want to remove a field from your database you need to remove from vTiger native UI.
