### ISSUE TITLE
Filename holder and Image doesn't save anything

### ISSUE THREAD

**Issue by ghost** [sardoj/VTModuleDesigner#135]
Hey there,
first of all I want to apologize for my bad english.
I designed a module using your VTModuleDesigner and tried to add an attachment (UI Type: Filename holder) and everything except the file upload works fine.
Index.php headers:
------WebKitFormBoundaryhthCpZ0FxYzyo3hW
Content-Disposition: form-data; name="attachment[]"; filename="dummy_pdf.pdf"
Content-Type: application/pdf

Some information:
- chmod is right
- the fileupload of other modules (for example documents) works fine
- no other external modules got installed
- vtiger version: 6.3 (and all patches for this version)

**Comment by playmono** [comment]
Hi,

Im sorry but as long as vTiger code will be hardcoded like this you will have problems doing this: you need to change some core files.

I recommend you to check **modules/Contacts/Contacts.php** function **save_module** and then **insertIntoAttachment**.and copy functionality to your module.

I recommend you to check **data/CRMEntity.php** (core file) function **uploadAndSaveFile** and wherever you see "Contacts" and "Products" try to add your condition for your module.

Checking this functions and doing some research you will achieve what you want.

Talking about VTModuleDesigner I think will be hard to doing feature like this.
