### ISSUE TITLE
Adding records in designer created module results in "Unknown column"

### ISSUE THREAD

**Issue by bthorben** [sardoj/VTModuleDesigner#139]
Steps to reproduce:
1. Create a new module with Designer
2. Install the module
3. Access the module and create a new record
4. Save the record

Expected:
The record is saved

Actual Result:
A page with an error-message including

> Unknown column 'vtiger_{module_name}cf.{module_name}id'

**Comment by playmono** [comment]
Hi,

This steps worked for me: 

I created a new module with one entity field. Then I installed and created a new record with no problems. 

I think steps are not very detailed to reproduce this issue.

**Comment by bthorben** [comment]
Way to go to push away a possible contributor!
