### ISSUE TITLE
Columns not appearing

### ISSUE THREAD

**Issue by Dinesh09** [sardoj/VTModuleDesigner#14]
Hi,
  I created a new module with vt module designer. Myself added three fields in lbl_general_information namely,  Date,Name(As identifier),operation,Related module as Organizations,contacts.

In vtiger_tab it shows all  the fields like  Date,Name,operation.But in vtiger_field table it shows only the date field. The module screen also not showing any other fields other than date.

I attached screenshots of tables and screen for reference. Help me to find the solution.                                                                                              

![vtiger_operations](https://f.cloud.github.com/assets/6869915/2356133/7ea7f5ee-a5e7-11e3-91f2-eb68686e524f.PNG)
![vtiger_field_tbl](https://f.cloud.github.com/assets/6869915/2356132/7ea568e2-a5e7-11e3-9eeb-0c7405867c55.PNG)
![lbl-general-information](https://f.cloud.github.com/assets/6869915/2356131/7ea0f0d2-a5e7-11e3-9ec6-2808e591196c.PNG)

```
                                                    thanks,
                                                                                              M.Dinesh Kumar.
```

**Comment by playmono** [comment]
Hi,
Module Designer failed for some reasons that we cant provide any solution without seeing any log.

I recommend you to try it again.
