### ISSUE TITLE
duplicate module

### ISSUE THREAD

**Issue by cosmibota** [sardoj/VTModuleDesigner#144]
I tried to make a new module from an existing one (Sales order) with _Load an existant module_ option but i got the next error when installing: "An error occured during installation. Please export the package an try to install it manually to see the error". At manual installation a got this error: "Invalid File provided for module import! Try Again." Any suggestions?

**Comment by sardoj** [comment]
Hello,

It is very complicated to duplicate core modules like Sales order because it uses several database tables and other things.
The best way is to create a base module with ModuleDesigner and then create views, models, actions, … manually.

**Comment by cosmibota** [comment]
OK, Thank you!
