### ISSUE TITLE
Sorry! Attempt to access restricted file.

### ISSUE THREAD

**Issue by McKenneii** [sardoj/VTModuleDesigner#146]
Hello,

i've made a module thanks to moduleDesigner on my dev server, I cna export it with no problems as a zip file, but when I install it on my production server the module isn't working (but it's working perfectly on my dev server).

When i try to access the module I have a white page with the error "Sorry! Attempt to access restricted file.".

I went into my into my vtiger folder, into the /modules folder , my module is not here, but he appears on Vtiger. Does anyone know why I have this error ? 

I would be glad to find why It's not working.

By the way I'm using Vtiger 6.0.0 .
EDIT: I can add that in my vtiger database, the tables related to my module have been created.
EDIT2 : My root directory in config.inc.php has the trailing slash as well.

Thanks for your answers,

With kindest regards,

**Comment by sardoj** [comment]
Hello, maybe you do not have write permission on your prod server, so the
files cannot be written.

**Comment by McKenneii** [comment]
Thanks @sardoj ! You made my day, didn't think about the rigths ...

Now it's working perfectly !
