### ISSUE TITLE
Unable to install yetiforce on localhost with port asignid 

### ISSUE THREAD

**Issue by aramxalil** [sardoj/VTModuleDesigner#147]
Dear Yetiforce Team 

1-Ican't install yetiforce using  e.g.( localhost:8020 or 192.168.1.77:8020)
when i try to install it, the system can't find database server witch is mysql , but when I try to install on localhost with out port it works (localhost)...

2- I can't use yetiforce from other pc on LAN

**Comment by GrisonDavid** [comment]
Hello Aramxalil.

I think you post this issue on the wrong Project.
You might contact the YetiForce here : https://github.com/YetiForceCompany/YetiForceCRM/issues

Regards.

**Comment by aramxalil** [comment]
I'm Sorry :(

**Comment by sanu-basak** [comment]
can i install yetiforce in local host
