### ISSUE TITLE
Not Displaying

### ISSUE THREAD

**Issue by jayo2005** [sardoj/VTModuleDesigner#17]
I uploaded the files to root vtiger 6 install. When I click settings and Templates VTModuleDesigner is not there?

**Comment by sardoj** [comment]
Hello,

You must install Module Designer via the Settings Panel.

**Comment by jayo2005** [comment]
I am trying to install through module manager. I get as far as verify Import details but only option I have is to click cancel. No option to go any further

![vtiger](https://f.cloud.github.com/assets/7015925/2482384/54fe0918-b0eb-11e3-91f8-6825a7e0edd0.PNG)

**Comment by sardoj** [comment]
I think it's because you're already uploaded files directly. First delete
all files, then try again to install properly the module.

**Comment by jayo2005** [comment]
Thanks that was it. I removed files I uploaded and it is now working,
