### ISSUE TITLE
Image name is not storing in database table/Image is not saved

### ISSUE THREAD

**Issue by DevangCP** [sardoj/VTModuleDesigner#20]
I set image field in new block. field is created in database table but after submitting data name of image is not displayed in records.
And also image is not saved anywhere.How to refetch it ?

**Comment by sardoj** [comment]
Hello,

It is not a bug of Module Designer.
You must develop several things to can upload images. You can look at the
"Product" module :

/modules/Products/actions/Save.php
/modules/Products/models/Record.php - getImageDetails()

**Comment by DevangCP** [comment]
Hello, 
Thanks for reply,

But i am very new to module development for vtiger.
Could you please guide me more for coding part ?

Cheers.
