### ISSUE TITLE
Error when trying to load module: String could not be parsed as XML

### ISSUE THREAD

**Issue by agilisgmbh** [sardoj/VTModuleDesigner#29]
Hi, i cant edit my module, as it shows the error:
"String could not be parsed as XML" - everytime, when i try to load and edit the created module.
How to solve?

regards from Austria

**Comment by playmono** [comment]
It's possible your Module has some fields/events/filters/whatever information with ilegal characters such as "&".

Open your manifest.xml in the root of your .rar module and search for "&" or maybe another strange character that you remember.

This is because XML files cant contain some characters.
