### ISSUE TITLE
quick How to

### ISSUE THREAD

**Issue by superlolo95** [sardoj/VTModuleDesigner#4]
Hello,
I am a French user and I recently installaded (on a clean VT6 instance) your module.
First congratulations for the work.

However, I am a bit lost on how to use it.
Mainly my questions are about the fileds:
-Dossier du module
-Manifest XM
What are those fields used to?
Is it possible to have a quick how to for those fields?

To clarify I am not a Vtiger expert so my request might be trivial.
Note: I also have anissue but a thread is already opend about it. So I will read it hoping it will help me to close it.

Thanks a lot.

**Comment by sardoj** [comment]
Bonjour,

Je suis français aussi.
Le champ "dossier du module" permet de choisir le template du répertoire
module. Il est possible d'en créer sois-même mais de base il existe soit un
répertoire pour les composants de type "module" (manipulation de données)
ou "extension" (sorte de plug-in Vtiger).
Le champ "manifest xml" permet de choisir si on veut créer un module ou une
extension. C'est lui qui va générer le fichier xml qui sera interprété par
Vtiger lors de l'installation du composant.

Cordialement,

Jonathan SARDO
[image: Images intégrées 5]
Tél. 06 99 45 50 47

2014-02-18 10:21 GMT+01:00 superlolo95 notifications@github.com:

**Comment by superlolo95** [comment]
Re bonjour Jonathan,
Merci pour la réponse extrêmement rapide.
Je regarde cela.
Je pense que le premier travail est pour moi de bien comprendre la notion module et extension :-)

**Comment by superlolo95** [comment]
Bonjour Jonathan,
J'aimerai créer 2 modules (très simples):
Partenaires (quelques champs de texte et un lien vers un ou plusieurs contacts)
Prescipteurs (quelques champs de texte et un lien vers un ou plusieurs contacts)

Je rencontre quelques difficultés avec VTModuleDesigner. Quelle documentation pourrais je lire pour apprendre à créer un module (et surtout comprendre les notions essentielles)?
J'aimerai initier la création avec VTModuleDesigner et ensuite décortiquer/ajuster les fichiers générés. Mais je n'ai aucune expérience sur les modules Vtiger (et même vtiger en général).

Merci

Loïc

**Comment by sardoj** [comment]
Bonjour Loïc,

Voici mon contact Skype, ce sera plus pratique pour discuter :
jonathan.sardo

Cordialement,

Jonathan SARDO

**Comment by jrajku** [comment]
Hi  Loïc,

If you found the solution, please share with us.

Thanks & Regards,
Raj

**Comment by superlolo95** [comment]
Hello,

If you are looking for the explanation of my first question which for Jonathan answered in french, below is the translation in English:
The field "dossier du module" (module folder) allow the choice of the forder module template. It is possible to create one  but by default one folder exits for the vtiger module (used for data manipulation) and another for the extensions (kind of Vtiger plugins).
The "manifest xml" field allows the selection between a module ceation or a plugin creation. It will generate the  xml file which will be read by vtiger during the component installation.

Regading the issue I had, did not investiguate deeply yet. Because I prefer to improve first my knowledge on Vtiger module and understand how VTDesignerModule is suppose to work.

My target is to create 2 simple modules:
-Partners (with some text attributes and related to sevral contacts)
-Prescriber (with some text attributes and related to sevral contacts)
I briefly tried to used Jonathan VTModuleDesigner but got errors.
So my objective is to first understand correctly how his module works and how to build vtiger modules. Maybe the best way to produce new modules would be to use VTDesignerModule first and then manually adapt the produced files.

**Comment by sardoj** [comment]
Hello,

Thanks for feedbacks.
I will try to record a video tutorial soon. It will be easier to understand.

Regards,
Jonathan

**Comment by jrajku** [comment]
Noted. Thanks.

**Comment by sardoj** [comment]
Here a link to Vtlib documentation :
https://www.vtiger.com/products/crm/help/5.2.0/VtigerCRM_5.2.0_Vtlib.pdf

Don't be afraid by "5.2.0" version. Vtlib still works the same.

Jonathan
