### ISSUE TITLE
Cannot import Designer File

### ISSUE THREAD

**Issue by emz3emz** [sardoj/VTModuleDesigner#45]
Dears I am new to VTIGER so can anyone guide me how to import designer to VTIGER 6 as i am trying to import mainfest files but always having this error so i think i am not doing the right action 

dUnzip2: ZIP File is corrupted or empty
 Warning: Invalid argument supplied for foreach() in C:\Program Files\vtigercrm600\apache\htdocs\vtigerCRM\vtlib\Vtiger\PackageImport.php on line 153

**Comment by emz3emz** [comment]
i want the steps for importing this >> "VTModuleDesigner" folder

**Comment by playmono** [comment]
Hi,

You need to overwrite your system core files with our folder called "patch".

**Comment by emz3emz** [comment]
i did that the 3 files , then i went to Import then I choosed manifest.xml on the src file but having the same error !

**Comment by emz3emz** [comment]
Dear Playmono it worked now :D i was importing .XML files and this was wrong i should have imported .zip folder :) many thanks
