### ISSUE TITLE
VTModuleDesigner 5.4

### ISSUE THREAD

**Issue by emz3emz** [sardoj/VTModuleDesigner#47]
Does this work for 5.4 version and if not what is the alternative ?

**Comment by playmono** [comment]
Hi, 

VTModuleDesigner dont works in 5.4. This version is intended for 6.0

The only solution I found for 5.4 is vtmodcreator http://forge.vtiger.com/projects/vtmodcreator/ but the last release was on December 8,2011 and the version is plenty of bugs.

**Comment by emz3emz** [comment]
many thanks Playmono 
the point is i want the VTIGER version that has phone call integration "Asterisks" and also the module designer 
i didnt find integration with Asterisks in 6 and i didnt find an easy module designer in v5.4 so what is the solutoin :(

**Comment by theopensourcerer** [comment]
@emz3emz vtiger 6.1.0 has Asterisk integration again. 

To be frank, it is pretty easy to write the bootstrap code to create a vtlib module by hand. It doesn't take very long once you've done it a few times...

**Comment by playmono** [comment]
Hi all,

This place on the internet, specifically in github, specifically on VTModuleDesigner issues, is to talk about VTModuleDesigner issues. Not other topics in any way.

Im sorry if I sound disrespectfully but please, for general vtiger questions, use the vtiger forum: https://discussions.vtiger.com/

Being said that, I close the issue.

**Comment by emz3emz** [comment]
so sorry Playmono be sure i wont ask here again

**Comment by emz3emz** [comment]
thanks @ theopensourcerer

**Comment by playmono** [comment]
No problem,

As I said, feel free to ask here if it's Module Designer related.

Regards
