### ISSUE TITLE
VTModuleDesigner compatability with VTIGER6.1

### ISSUE THREAD

**Issue by emz3emz** [sardoj/VTModuleDesigner#48]
does this work on 6.1 because i tried to import it and succeeded ? so will it work fine or not ?

**Comment by sardoj** [comment]
With Vtiger 6.1, /libraries/csrf-magic/csrf-magic.php (line 175) adds in all iframes:

<script type="text/javascript">if (top != self) {top.location.href = self.location.href;}</script>

I fixed this bug adding in all views:
$GLOBALS['csrf']['frame-breaker'] = false;
