### ISSUE TITLE
Import module depuis vtiger 5.4

### ISSUE THREAD

**Issue by apcloic** [sardoj/VTModuleDesigner#5]
Bonjour Jonathan,

Tout d'abord, un grand merci pour votre module, je pense que c'est une contribution inestimable pour l'avenir de la version open source de vtiger ;)
Je suis en train de faire quelques essais sur une version fraîchement installée.
Dans un 1er temps, je cherche à convertir un ancien module assez basique intitulé "phplistsync" qui permet de synchroniser la base des contacts avec l'outil d'emailing phplist.
A priori il s'agit donc d'un module de type "extension", j'ai simplement : 
- chargé le module
- défini les noms de traductions
- générer et installer.
  --> bon, visiblement il y a d'autres étapes car au final le fichier du module est pratiquement vide et lorsque l'on va dessus on obtient l'erreur suivante :

Warning: in_array() expects parameter 2 to be array, null given in /var/www/vtigercrm6/include/Webservices/VtigerCRMObjectMeta.php on line 44 Warning: Invalid argument supplied for foreach() in /var/www/vtigercrm6/include/QueryGenerator/QueryGenerator.php on line 172 Warning: Invalid argument supplied for foreach() in /var/www/vtigercrm6/include/QueryGenerator/QueryGenerator.php on line 172 Warning: array_flip(): Can only flip STRING and INTEGER values! in /var/www/vtigercrm6/modules/Vtiger/models/Module.php on line 199

Ci-dessous le module que je cherche à importer :
https://www.dropbox.com/s/tykvdobocbfoqi4/PHPListSync-1.0.0.zip
Et le résultat une fois importé :
https://www.dropbox.com/s/mx5gvnd4vpt10a7/PHPListSync_2014-02-20_1.0.0.zip

Si vous avez des pistes pour les étapes nécessaire, je suis preneur.
Merci d'avance,
Cdlt,

**Comment by sardoj** [comment]
Bonjour,

Ça va etre difficile, étant donné que Module Designer n'est pas capable que
convertir toute la logique (les scripts) de Vtiger 5.4 à Vtiger 6.
Il est juste capable que de convertir un module Vtiger 5.4 (de type module)
en module Vtiger 6 et créer tous les champs et tables nécessaires.
Pour cela il faudra choisir dans "Dossier du module", la valeur "6.0.0" au
lieu de "dossier du module", une fois le module uploadé.

Cordialement,

Jonathan

**Comment by apcloic** [comment]
Ok, c'est tout à fait clair.
Merci bcp Jonathan pour ces explications.
Bonne soirée,
Cdlt,

**Comment by mak5** [comment]
Bonjour apcloic,
J'ai le même problème que vous, je cherche une solution pour l’intégration de phplist avec vtiger 6.
Le seul module qui existe est  "phplistsync" depuis 2010.
Ma question est avez-vous trouvé une solution pour importer le module vers vtiger 6 ?
Si vous avez trouvé une autre solution je serai très ravi si vous m'informer 
Merci.
