### ISSUE TITLE
Permission to perform the operation is denied for name

### ISSUE THREAD

**Issue by metastatic** [sardoj/VTModuleDesigner#62]
When creating a module if "\* Custom Name *" is selected from the 'Menu' picklist for the 'Related Menu' section the following error is returned when the module is selected from the vTiger menu-:

"Permission to perform the operation is denied for name"

I'm using vTiger 6.1.0

**Comment by metastatic** [comment]
![image](https://cloud.githubusercontent.com/assets/9609784/4953868/352cc808-6686-11e4-82e0-c92262123656.png)

For this module I added just one custom field called 'name'

![image](https://cloud.githubusercontent.com/assets/9609784/4953883/6256f358-6686-11e4-85f9-e5723285f16b.png)

![image](https://cloud.githubusercontent.com/assets/9609784/4953891/7cb118f0-6686-11e4-94ba-4d699b69d54d.png)

After the module is installed it is presented as the following in the vTiger menu

![image](https://cloud.githubusercontent.com/assets/9609784/4953901/b6751064-6686-11e4-927a-1869733ff523.png)

Selecting TestMods17 results in the following-:

![image](https://cloud.githubusercontent.com/assets/9609784/4953911/c90bb502-6686-11e4-8565-3b2b0f07776e.png)

**Comment by whoisbrianroberts** [comment]
I have the same issue, but I spent more than 1 hour building this module out and got the same error.

**Comment by sardoj** [comment]
Hi!
I will try to fix this bug. I don't know why but the bug is caused because a row is not created into the table "vtiger_ws_entity". @metastatic @whoisbrianroberts you can fix this bug, simply duplicating a row and put the module's name into "name" column.﻿

**Comment by metastatic** [comment]
Hi sardoj. 

Thanks for the response. 
1. I can confirm that duplicating a row in the 'vtiger_ws_entity' table and then modifying the 'id' and 'name' columns does indeed resolve the "Permission to perform the operation is denied for name" error. Unfortunately a number of issues still exist after adding the row to the table. For example, when I attempt to add a record to the new module the fields are missing and when I click submit to add the record the following error is returned, "LBL_MANDATORY_FIELD_MISSING". This is with the latest patch installed.

**Comment by apcloic** [comment]
@metastatic This is because your new module's tables are not created. I don't know why but I've faced the same issue.
So, in order to resolve this : 
- Export your module as zip file
- Edit manifest.xml to increment module version (for example move from 1.0 to 1.1) 
- Save your zip with modified manifest.xml
- Import/Update your module back
  You should now see your module's tables so it should work (at least, it works for me).
  Thanks to Jonathan for making his module compatible with vTiger 6.1
  Regards,

**Comment by metastatic** [comment]
@apcloic Thank you for your message. Unfortunately your solution did not work for me.

**Comment by whoisbrianroberts** [comment]
I think the problem here is the field can not be called name, I started build a new module and have not have this problem. No fields called name.

Love this module man! Just wish you had more docs or videos on how to use all the functions in-depth.
This one module alone changes everything you know about CRMs! You just wait and see!

**Comment by metastatic** [comment]
@whoisbrianroberts thanks for your reply. I've just created another module with a different field name. Unfortunately the issue still occurs if "\* Custom Name *" is selected from the 'Menu' picklist for the 'Related Menu' section.

**Comment by whoisbrianroberts** [comment]
I never used Custom Name for the menu.

**Comment by apcloic** [comment]
@metastatic Sorry to hear that it doesn't work for you.
Did you check your database ? Is your module's table created ?
Did you see any error when importing back your module ?

**Comment by metastatic** [comment]
@apcloic Ok I think I now understand what you mean. 

Providing one exports their module as a zip file before exiting Module Designer it is possible to load the failed module back in as an existant module and make the necessary changes (i.e. set the menu to a known value). It is essential that a row is added to 'vtiger_ws_entity' table too otherwise the menu value does not change.

**Comment by kiransingh1117** [comment]
@sardoj  I had one project in vTiger CRM 6.0 version then I installed module designer which was compatible with vTiger 6.0 but after releasing new version of vTiger 6.1  we have upgraded vTiger 6.0 into vTiger 6.1 and then tried to create new module through module designer but it shown error and when I clicked on newly created module through menu bar then it shown "Permission to perform the operation is denied for name". I resolved this error by adding new row in "vtiger_ws_entity" table for newly created module, but when I added new record then again shown error "result is not an object". Even I have deleted old module designer and reinstall new version which is available here "https://github.com/sardoj/VTModuleDesigner"  but still faced same issue when I am trying to create new module through module designer version 6.1, shown error, when clicked on this newly created module, shown "Permission to perform the operation is denied for name" "  and then added new row in  "vtiger_ws_entity" table and then error "Permission to perform the operation is denied for name" resolved but after added new record page becomes blank and after clicking on this module through menu bar again it shows "result is not an object". 

Please let me know how can I resolve this error, I have tried a lot but did not get any successful solution

Please give me proper solution asap..

Thanks in advance,
Kiran Singh

**Comment by sardoj** [comment]
Fixed new 1.0 RC version
