### ISSUE TITLE
Make label translations not be all mandatory

### ISSUE THREAD

**Issue by makerdrone** [sardoj/VTModuleDesigner#67]
Right now in the field edit form when you try to save and you have not put in all available label translations it does not allow you to save.

![screenshot from 2014-12-01 21 06 28](https://cloud.githubusercontent.com/assets/5627346/5251436/06e25a28-799e-11e4-8625-c6807ca78b3c.png)

This is especially annoying when there are many translations available and you want to support only one or two.

My suggestion is to let there be one mandatory label translation and the rest to be optional.
For example at least one of the translations(not any specific one, just any of them) to need to be filled to be allowed to save - like the module name translations.

**Comment by sardoj** [comment]
Fixed in 1.0 RC version
