### ISSUE TITLE
Having blank index.php page when save record in new custom module

### ISSUE THREAD

**Issue by mask207** [sardoj/VTModuleDesigner#7]
Hello, I have blank index.php page every time I click save button to save record from new custom module created with VTModuleDesigner. I create and see all info is saved but I'm not sure if something can go wrong behind the blank page. Can you check it ?

**Comment by samhast** [comment]
do you have an indentifier field? Is necessary. I had that problem to, but when I added an identifier field = problem solved

**Comment by mask207** [comment]
Thank you, identifier field solved the problem. 
I have another question. I'm trying to create a module using existing inventoryproductrel table and it's fields when I add fields to Block & Fields tab in Module Designer.
After making the module, i have this error when I save record:
{"success":false,"error":{"code":"Record you are trying to access is not found","message":"Record you are trying to access is not found"}}
If I let Module Designer creates new table (same name as module name) then everything is fine. 
Is it possible to use existing tables & fields for new custom module ?

**Comment by mask207** [comment]
Don't worry about it, i figured out the issue. The php file from modules/[modulename] has setting of new fields under new table in database, change table in Module Designer doesn't carry the table setting to this file. So the file need to be modified.
