### ISSUE TITLE
Module created through VTModuleDesigner not working with upgraded version of vtiger 6.1

### ISSUE THREAD

**Issue by arpitvaish** [sardoj/VTModuleDesigner#70]
Hi,

I have had a very strange error. I have installed VTmoduledesigner in one of my vtiger installation (i.e. version 6.1). I created module through this and did "Make and install the module", works fine. However when I download the zip package and install it on one of my Vtiger installation that is migrated from 6.0 to  6.1 give me error. Although when I install the same on 6.0 version works fine. Here is what I am getting : 
![vtiger error](https://cloud.githubusercontent.com/assets/5059896/5370225/653245a4-8045-11e4-9f5d-7db0f707da9d.png)

**Comment by yvesripoll** [comment]
Just delete all ModuleDesigner directories in your /var/www/html/vtiger/... , and then the ZIP module file will be import correctly.

**Comment by kiransingh1117** [comment]
@sardoj  I had one project in vTiger CRM 6.0 version then I installed module designer which was compatible with vTiger 6.0 but after releasing new version of vTiger 6.1  we have upgraded vTiger 6.0 into vTiger 6.1 and then tried to create new module through module designer but it shown error and when I clicked on newly created module through menu bar then it shown "Permission to perform the operation is denied for name". I resolved this error by adding new row in "vtiger_ws_entity" table for newly created module, but when I added new record then again shown error "result is not an object". Even I have deleted old module designer and reinstall new version which is available here "https://github.com/sardoj/VTModuleDesigner"  but still faced same issue when I am trying to create new module through module designer version 6.1, shown error, when clicked on this newly created module, shown "Permission to perform the operation is denied for name" "  and then added new row in  "vtiger_ws_entity" table and then error "Permission to perform the operation is denied for name" resolved but after added new record page becomes blank and after clicking on this module through menu bar again it shows "result is not an object". 

Please let me know how can I resolve this error, I have tried a lot but did not get any successful solution

Please give me proper solution asap..

Thanks in advance,
Kiran Singh

**Comment by arpitvaish** [comment]
Thanks Sardoj.. works now!
