### ISSUE TITLE
How to develop custom view?

### ISSUE THREAD

**Issue by brundles** [sardoj/VTModuleDesigner#77]
Hi :)

Again, thanks for an excellent module :)

I have a quick question: How can I design a custom view? Ie. lets say I want a table with some values horisontal (dates) and other values veritcally (tasks) and then list my entries from the module in this table.

I can obviously do the coding myself, but just need a pointer to where I could (manually) add the views?

Thanks in advance :)

**Comment by sardoj** [comment]
Hi

You can't do this with ModuleDesigner. You can clone a view file from
modules/Vtiger/views directory and do the same, extending the right Vtiger
class.

**Comment by brundles** [comment]
Ok - I guessed that I'd somehow have to do it manually, which is no problem - its still 500% easier to start with ModuleDesigner than from scratch :-D

I've looked a little in the modules/Vtiger/views directory and can see all the list-view etc. to clone from.

How would I use a view in the newly created module? Ie. if we take Dashboard or other existing view as an example?

**Comment by sardoj** [comment]
modules/Leads/views/ConvertLead.php is a good example

If you want custom developments you can contact me on Skype to have a
quotation: jonathan.sardo
