### ISSUE TITLE
Problems with German Lang (ü,ö, ä, etc) and cannot delete Fields

### ISSUE THREAD

**Issue by agilisgmbh** [sardoj/VTModuleDesigner#82]
Hi there,
I´ve successful added german language to ModuleDesigner.
Anyway, when I use Ö Ä Ü etc, cannot edit my module again! Need to change back in regular fieldeditor to "ae, oe, ue" then i can start working with the moduledesinger again.
Can you fix this issue with ö,ä,ü, etc?

Another very very important thing is, that i cant delete fields created in the module (deleting directly in MD):
Most time, there´s not Trash-Icon coming up, but IF its there, and i drag it into the trash, it does not DELETE correctly.
Any Ideas?

**Comment by sardoj** [comment]
See new 1.0 RC version
