### ISSUE TITLE
How Can I do this? Custom Module shown on Accounts module

### ISSUE THREAD

**Issue by nikomaxia** [sardoj/VTModuleDesigner#83]
Hi to all and may all of you have a happy new year!
I have create a new custom module named "FIXED" In the related list tab of the module designer, I have choose "Accounts" with the "get_related_list" method.

When I open the "FIXED" module everything is look fine and I can add records with no problems!
I also have a field which is related with the Name of the Accounts module.
My question is: When I am in the "Acoounts" module I cannot see at the right sidebar the Fixed module (see photo below)
How Can I add this?

Thanks guys

![image](https://cloud.githubusercontent.com/assets/9491662/5645861/9f5ac154-967d-11e4-8730-1fa4c09a311e.png)

**Comment by metastatic** [comment]
Install and use this extension

https://shop.stefanwarnat.de/vtigercrm-tools/

**Comment by nikomaxia** [comment]
Thanks metastatic!!! Awesome module! Did the job!!!!

**Comment by metastatic** [comment]
You're welcome :)

**Comment by swim89** [comment]
Thanks, I downloaded and installed the module....but I have a problem...when I go to Account right sidebar created, I saw the module but with empty list like attach...
![error](https://cloud.githubusercontent.com/assets/2925880/6215898/2011dd86-b605-11e4-8223-34baaab3b42e.JPG)

**Comment by sardoj** [comment]
With Module Designer v1.0 RC, you can now edit Vtiger core's modules and add for example Related Lists.
