### ISSUE TITLE
VTModuleDesigner for vtiger 6.1.0 ?

### ISSUE THREAD

**Issue by hasanhms** [sardoj/VTModuleDesigner#84]
good morning

i installed and used VTModuleDesigner for vtiger 6.0.0 .
it is great. it is the best tool for vtiger. thanks.

Have you upgraded VTModuleDesigner for vtiger 6.1.0 ?

regards

**Comment by sardoj** [comment]
Hi !
You can download the last version here : www.mediatoolbox.org

Cordialement,

Jonathan SARDO
[image: Images intégrées 5]
Tél. 06 99 45 50 47

2015-01-09 16:53 GMT+01:00 hasab notifications@github.com:

**Comment by hasanhms** [comment]
dear Sardo
the link is ecommerce site. 
i made an order for the package. 
checked it through out the check-out-process, 
but the product is not downloaded.
awaiting.
thanks

**Comment by sardoj** [comment]
You have to go to the order detail and there is a link to download
ModuleDesigner.

## 

Cordialement,

Jonathan SARDO
[image: Images intégrées 5]
Tél. 06 99 45 50 47
