### ISSUE TITLE
Import Impossible

### ISSUE THREAD

**Issue by GrisonDavid** [sardoj/VTModuleDesigner#87]
Salut, il me semble que tu es français donc j'en profite un peu.
Je n'arrive pas à importer ton module.
Je suis pourtant sous Vtiger 6.1 et j'ai bien ton module 6.1.
Mais le manifest.xml est introuvable lors de l'import qui est dans src/, et si je le bouge de place pour le mettre à la racine du zip, impossible de confirmer les informations par la suite.
Une idée d'ou pourrai venir le problème?
Cordialement.

Je la fait en anglais pour les anglophones.
Can't import your module 6.1 because manifest.xml is not found
If i move it in the src/, it run, but at the next step to confirm information, no button ok.
so, can you help me?

**Comment by sardoj** [comment]
Bonjour,

C'est parce que tu télécharges les sources au lieu de télécharger le
package .zip du module.
Tu peux retrouver ce package sur le site www.mediatoolbox.org

**Comment by GrisonDavid** [comment]
J'ai bien téléchargé sur Mediatoolbox, et rien ne change, arrivé à la derniere etape, pas de bouton ok pour "Verifier les informations avant l'import".

**Comment by sardoj** [comment]
Ok c'est parce que tu as du ajouter le répertoire directement sur le
serveur avant l'import.
Le plus simple et de supprimer toutes les références à ModuleDesigner dans
le répertoire /modules
Tu pourras ensuite installer le .zip

**Comment by GrisonDavid** [comment]
Super!
Marche parfaitement, plus qu'a regarder ta video pour faire ce que je veux ;)
Bonne continuation.

**Comment by sardoj** [comment]
Super !

Pour info je suis en train d'enregistrer une longue vidéo qui expliquera en
détail tout ce qu'on peut faire avec ModuleDesigner.
J'espère que je pourrai la terminer bientôt.

**Comment by GrisonDavid** [comment]
https://github.com/sardoj/VTModuleDesigner/issues/71
  / \
  ||
English version
