### ISSUE TITLE
Cannot load an existing module

### ISSUE THREAD

**Issue by jeangarzon** [sardoj/VTModuleDesigner#88]
Hi, i have vtiger 6.1 and module designer 1.0b1.1. My issue is when i try to load an existing module from the module designer, the web browser says " An error ocurred. PLease try again" so i cannot load it. This happens just with some modules. It happens with "Accounts", "Leads", "Potentials", "sales orders", "services contracts". The other modules can be loaded fine. Any ideas of what is happening to solve this issue?
BR.

**Comment by sardoj** [comment]
Yes i know. Vtiger modules are not implemented like custom modules and you
can't edit all core modules... Maybe somebody can help me to debug this...

## 

Cordialement,

Jonathan SARDO
[image: Images intégrées 5]
Tél. 06 99 45 50 47

**Comment by jeangarzon** [comment]
HI Jonathan, thanks for your prompt answer. I had noticed in other PC where i have installed a mirror of vtiger just for tests, that when i try to load "sales orders" module and it works fine with empty databases, but when i restore a backup to the mirror system it happens the same error than with the main system.

**Comment by sardoj** [comment]
Fixed in 1.0 RC version. You can now modify core's modules.
