### ISSUE TITLE
Import Module on Module Designer

### ISSUE THREAD

**Issue by fyudelgado** [sardoj/VTModuleDesigner#93]
Hi,

I was install a fresh version of Vtiger 6.1 with Module Designer. I made a new Module, and the module was installed fine, and it's fully functional. When I try to Import the module into Module Designer, popup a message that an error was produced. The apache log server send the next line warning:

PHP Warning:  implode(): Invalid arguments passed in /var/www/vtigercrm/modules/Settings/ModuleDesigner/actions/GetManifestStructure.php on line 383, referer: http://Server/index.php?module=ModuleDesigner&view=Index&parent=Settings&block=2&fieldid=33

And no module is loaded into the Module Designer.

Using: Apache 2
PHP  5.5.9-1ubuntu4.5
MySql 5.5.41-0ubuntu0.14.04.1

Could you help me whats wrong?

Regards,
Francisco Yu

**Comment by sardoj** [comment]
Fixed in 1.0 RC version
