### ISSUE TITLE
Attendances module

### ISSUE THREAD

**Issue by johnistas** [sardoj/VTModuleDesigner#95]
I have a dance teaching school.

I have my contacts, my services and my service contracts.

And i want to record attendances for my membership members. Who came and who didnt.

For example there is Mary, Helen and Jones who have taken one dance membership. And only Mary and Helen had come at a certain lesson a certain date. 
Jones didnt come.

How can i make a list or report from which member they came and which the did not.

Any ideas?

**Comment by sardoj** [comment]
Hello,

This bugs tracker is dedicated to Module Designer's bugs not for support in
Vtiger.

But here a solution to your problem: you can use the Reports Module of
Vtiger.

**Comment by johnistas** [comment]
ok thanks sardoj

**Comment by johnistas** [comment]
ok thanks
