### ISSUE TITLE
How can i change language

### ISSUE THREAD

**Issue by johnistas** [sardoj/VTModuleDesigner#96]
I want to change the language of the names of the modules on related lists in the right bar..

I change the language ini file but i cant do it. It shows the label name. 

How can i do it?

**Comment by GrisonDavid** [comment]
Change it in the languages folder.
Select your language, find your module and change tke first line 
$languageStrings = array(
'yourModuleName' => 'traduction',
...
...
);
change "traduction" by your need.

**Comment by johnistas** [comment]
Didnt explain it clearly.

I want to change the language only in the right bar (related module) but keep the same in the upper bar (main module).

For example:
"Contacts" in the upper bar but
"Attendances" in the right bar(related) in my module

I want to take contacts but be named something else.

When i write in my module  'Contacts' => 'Attendances' it continues to show "Contacts"

Thank you

**Comment by sardoj** [comment]
You can choose a different label for the Related List, for example :
LBL_ATTENDANCES and translate it into "Attendances"

**Comment by johnistas** [comment]
thank you

**Comment by johnistas** [comment]
Also not to open a new issue..

Do you know how to add my new module to be shown in others modules related lists

e.g.
In an existed contact put in related modules the costume module i just created. I cant check it in settings..

**Comment by sardoj** [comment]
Load Contacts module, go to Related List tab, and add a related list with
your custom module.

**Comment by johnistas** [comment]
Cant load the contacts module

"The page at localhost says
An error occurred. Please try again later"

**Comment by sardoj** [comment]
Did you install the new version of Module Designer?
V0.1 RC
Don't forget to update the browser's cache?

## 

Cordialement,

Jonathan SARDO
Tél. 06 99 45 50 47

**Comment by johnistas** [comment]
Thank you so much!!
